#!/bin/sh
### BEGIN INIT INFO
# Provides:          rtorrentd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the rtorrent server as a daemon.
### END INIT INFO


PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin
DAEMON=rtorrent
USER=jason
NAME=rtorrent
DESC="rtorrent as a daemon"
SCRIPTNAME=/etc/init.d/rtorrentd


. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC"
        if su - $USER -c "/usr/bin/tmux new-session -s rt -n $DAEMON -d $NAME"
        then
            if [ "$(pidof $DAEMON)" ]
            then
                log_end_msg 0
            else
                log_end_msg 1
            fi
        else
            log_end_msg 1
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $DESC"
        if su - $USER -c "/usr/bin/tmux send-keys -t rt:$DAEMON C-q"
        then
            while [ "$(pidof $DAEMON)" ]; do
                echo -n "."
                sleep 1s
            done
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    restart)
        $0 stop
	sleep 1s
        $0 start
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
